// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Image                []byte               `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Price                int64                `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Description          string               `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Username             string               `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Location             string               `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Deadline             *timestamp.Timestamp `protobuf:"bytes,9,opt,name=deadline,proto3" json:"deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Post) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Post) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Post) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Post) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Post) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Post) GetDeadline() *timestamp.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

type CreatePostReq struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostReq) Reset()         { *m = CreatePostReq{} }
func (m *CreatePostReq) String() string { return proto.CompactTextString(m) }
func (*CreatePostReq) ProtoMessage()    {}
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CreatePostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostReq.Unmarshal(m, b)
}
func (m *CreatePostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostReq.Marshal(b, m, deterministic)
}
func (m *CreatePostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostReq.Merge(m, src)
}
func (m *CreatePostReq) XXX_Size() int {
	return xxx_messageInfo_CreatePostReq.Size(m)
}
func (m *CreatePostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostReq proto.InternalMessageInfo

func (m *CreatePostReq) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *CreatePostReq) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type CreatePostResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreatePostResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type ReadPostReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPostReq) Reset()         { *m = ReadPostReq{} }
func (m *ReadPostReq) String() string { return proto.CompactTextString(m) }
func (*ReadPostReq) ProtoMessage()    {}
func (*ReadPostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *ReadPostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPostReq.Unmarshal(m, b)
}
func (m *ReadPostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPostReq.Marshal(b, m, deterministic)
}
func (m *ReadPostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPostReq.Merge(m, src)
}
func (m *ReadPostReq) XXX_Size() int {
	return xxx_messageInfo_ReadPostReq.Size(m)
}
func (m *ReadPostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPostReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPostReq proto.InternalMessageInfo

func (m *ReadPostReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadPostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadPostResponse) Reset()         { *m = ReadPostResponse{} }
func (m *ReadPostResponse) String() string { return proto.CompactTextString(m) }
func (*ReadPostResponse) ProtoMessage()    {}
func (*ReadPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *ReadPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadPostResponse.Unmarshal(m, b)
}
func (m *ReadPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadPostResponse.Marshal(b, m, deterministic)
}
func (m *ReadPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadPostResponse.Merge(m, src)
}
func (m *ReadPostResponse) XXX_Size() int {
	return xxx_messageInfo_ReadPostResponse.Size(m)
}
func (m *ReadPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadPostResponse proto.InternalMessageInfo

func (m *ReadPostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type UpdatePostReq struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostReq) Reset()         { *m = UpdatePostReq{} }
func (m *UpdatePostReq) String() string { return proto.CompactTextString(m) }
func (*UpdatePostReq) ProtoMessage()    {}
func (*UpdatePostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *UpdatePostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostReq.Unmarshal(m, b)
}
func (m *UpdatePostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostReq.Marshal(b, m, deterministic)
}
func (m *UpdatePostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostReq.Merge(m, src)
}
func (m *UpdatePostReq) XXX_Size() int {
	return xxx_messageInfo_UpdatePostReq.Size(m)
}
func (m *UpdatePostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostReq proto.InternalMessageInfo

func (m *UpdatePostReq) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *UpdatePostReq) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type UpdatePostResponse struct {
	Updated              int64    `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostResponse) Reset()         { *m = UpdatePostResponse{} }
func (m *UpdatePostResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePostResponse) ProtoMessage()    {}
func (*UpdatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *UpdatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostResponse.Unmarshal(m, b)
}
func (m *UpdatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostResponse.Merge(m, src)
}
func (m *UpdatePostResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePostResponse.Size(m)
}
func (m *UpdatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostResponse proto.InternalMessageInfo

func (m *UpdatePostResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *UpdatePostResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type ReadAllRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllRequest) Reset()         { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()    {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllRequest.Unmarshal(m, b)
}
func (m *ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllRequest.Merge(m, src)
}
func (m *ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllRequest.Size(m)
}
func (m *ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllRequest proto.InternalMessageInfo

func (m *ReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type ReadAllResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *ReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type DeletePostReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostReq) Reset()         { *m = DeletePostReq{} }
func (m *DeletePostReq) String() string { return proto.CompactTextString(m) }
func (*DeletePostReq) ProtoMessage()    {}
func (*DeletePostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *DeletePostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostReq.Unmarshal(m, b)
}
func (m *DeletePostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostReq.Marshal(b, m, deterministic)
}
func (m *DeletePostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostReq.Merge(m, src)
}
func (m *DeletePostReq) XXX_Size() int {
	return xxx_messageInfo_DeletePostReq.Size(m)
}
func (m *DeletePostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostReq proto.InternalMessageInfo

func (m *DeletePostReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DeletePostReq) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type DeletePostResponse struct {
	Deleted              int64    `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostResponse) Reset()         { *m = DeletePostResponse{} }
func (m *DeletePostResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePostResponse) ProtoMessage()    {}
func (*DeletePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *DeletePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostResponse.Unmarshal(m, b)
}
func (m *DeletePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostResponse.Marshal(b, m, deterministic)
}
func (m *DeletePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostResponse.Merge(m, src)
}
func (m *DeletePostResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePostResponse.Size(m)
}
func (m *DeletePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostResponse proto.InternalMessageInfo

func (m *DeletePostResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func (m *DeletePostResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "proto.Post")
	proto.RegisterType((*CreatePostReq)(nil), "proto.CreatePostReq")
	proto.RegisterType((*CreatePostResponse)(nil), "proto.CreatePostResponse")
	proto.RegisterType((*ReadPostReq)(nil), "proto.ReadPostReq")
	proto.RegisterType((*ReadPostResponse)(nil), "proto.ReadPostResponse")
	proto.RegisterType((*UpdatePostReq)(nil), "proto.UpdatePostReq")
	proto.RegisterType((*UpdatePostResponse)(nil), "proto.UpdatePostResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "proto.ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "proto.ReadAllResponse")
	proto.RegisterType((*DeletePostReq)(nil), "proto.DeletePostReq")
	proto.RegisterType((*DeletePostResponse)(nil), "proto.DeletePostResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xf3, 0xd1, 0x24, 0x63, 0x52, 0xaa, 0x55, 0x81, 0xc5, 0x12, 0xaa, 0xf1, 0x29, 0x27,
	0x57, 0xa4, 0x52, 0x81, 0x43, 0xa5, 0x06, 0x10, 0x67, 0x64, 0xe0, 0x8c, 0xb6, 0xde, 0x21, 0x5a,
	0xc9, 0xc9, 0xba, 0xde, 0x0d, 0xff, 0x88, 0x7f, 0xc1, 0x8f, 0x43, 0xde, 0x5d, 0x7b, 0x9d, 0xc4,
	0x52, 0x0e, 0x3d, 0x25, 0xf3, 0x66, 0xde, 0xbc, 0x99, 0xb7, 0x63, 0x98, 0x2b, 0xac, 0xfe, 0x88,
	0x1c, 0xd3, 0xb2, 0x92, 0x5a, 0x92, 0xb1, 0xf9, 0x89, 0xae, 0xd6, 0x52, 0xae, 0x0b, 0xbc, 0x36,
	0xd1, 0xc3, 0xee, 0xf7, 0xb5, 0x16, 0x1b, 0x54, 0x9a, 0x6d, 0x4a, 0x5b, 0x97, 0xfc, 0x1d, 0xc0,
	0xe8, 0x9b, 0x54, 0x9a, 0x9c, 0xc3, 0x40, 0x70, 0x1a, 0xc4, 0xc1, 0x62, 0x98, 0x0d, 0x04, 0x27,
	0x97, 0x30, 0xd6, 0x42, 0x17, 0x48, 0x07, 0x71, 0xb0, 0x98, 0x65, 0x36, 0xa8, 0x51, 0xb1, 0x61,
	0x6b, 0xa4, 0xc3, 0x38, 0x58, 0x3c, 0xcb, 0x6c, 0x50, 0xa3, 0x65, 0x25, 0x72, 0xa4, 0x23, 0x43,
	0xb7, 0x01, 0x89, 0x21, 0xe4, 0xa8, 0xf2, 0x4a, 0x94, 0x5a, 0xc8, 0x2d, 0x1d, 0x9b, 0x3e, 0x5d,
	0x88, 0x44, 0x30, 0xdd, 0x29, 0xac, 0xb6, 0x6c, 0x83, 0xf4, 0xcc, 0xa4, 0xdb, 0xb8, 0xce, 0x15,
	0x32, 0x67, 0x86, 0x3a, 0xb1, 0xb9, 0x26, 0x26, 0x1f, 0x01, 0xf2, 0x0a, 0x99, 0x46, 0xfe, 0x8b,
	0x69, 0x3a, 0x8d, 0x83, 0x45, 0xb8, 0x8c, 0x52, 0xbb, 0x6a, 0xda, 0xac, 0x9a, 0xfe, 0x68, 0x56,
	0xcd, 0x66, 0xae, 0x7a, 0xa5, 0xc9, 0x2d, 0x4c, 0x39, 0x32, 0x5e, 0x88, 0x2d, 0xd2, 0xd9, 0x49,
	0x62, 0x5b, 0x9b, 0x7c, 0x82, 0xf9, 0x67, 0xd3, 0xa4, 0x36, 0x2b, 0xc3, 0x47, 0x72, 0x05, 0xa3,
	0x52, 0x2a, 0x6d, 0x1c, 0x0b, 0x97, 0xa1, 0x65, 0xa7, 0x26, 0x6b, 0x12, 0xe4, 0x02, 0x86, 0xac,
	0x14, 0xce, 0xbe, 0xfa, 0x6f, 0x72, 0x0b, 0xa4, 0xdb, 0x43, 0x95, 0x72, 0xab, 0xf0, 0xc8, 0xf8,
	0x63, 0xde, 0x1b, 0x08, 0x33, 0x64, 0xbc, 0x51, 0x3e, 0x20, 0x24, 0x37, 0x70, 0xe1, 0xd3, 0xae,
	0xe9, 0xa9, 0xe9, 0xea, 0x7d, 0x7e, 0x96, 0xfc, 0x69, 0xfb, 0xdc, 0x03, 0xe9, 0xf6, 0x70, 0xd2,
	0x14, 0x26, 0x3b, 0x83, 0x36, 0x33, 0x36, 0x61, 0x4f, 0x87, 0x04, 0xce, 0xeb, 0xd1, 0x57, 0x45,
	0x91, 0xe1, 0xe3, 0x0e, 0xbd, 0x4a, 0xe0, 0x6b, 0xbe, 0xc2, 0xf3, 0xb6, 0xc6, 0x49, 0xbc, 0x85,
	0x71, 0x3d, 0x92, 0xa2, 0x41, 0x3c, 0x3c, 0x1c, 0xd6, 0x66, 0x7a, 0xb4, 0xde, 0xc1, 0xfc, 0x0b,
	0x16, 0xe8, 0x37, 0x3e, 0x6d, 0xfc, 0x3d, 0x90, 0x2e, 0xc5, 0x2f, 0xc8, 0x0d, 0xda, 0x2e, 0xe8,
	0xc2, 0xe3, 0x0e, 0xcb, 0x7f, 0x03, 0x80, 0x15, 0xe7, 0xdf, 0xed, 0xb7, 0x49, 0xee, 0x00, 0xfc,
	0x05, 0x90, 0x4b, 0x37, 0xf7, 0xde, 0x61, 0x45, 0xaf, 0x7b, 0x50, 0xa7, 0x7c, 0x07, 0xe0, 0x0d,
	0x6f, 0xe9, 0x7b, 0xef, 0xd8, 0xd2, 0x7b, 0x5e, 0xe6, 0x3d, 0x4c, 0x9b, 0x43, 0x21, 0xc4, 0x95,
	0x75, 0x0e, 0x2b, 0x7a, 0x75, 0x84, 0x79, 0x5d, 0xef, 0x43, 0xab, 0xbb, 0xe7, 0x66, 0xab, 0xdb,
	0x63, 0xd8, 0x07, 0x98, 0xb8, 0x17, 0x24, 0x2f, 0x3a, 0x12, 0xfe, 0xd5, 0xa3, 0x97, 0x87, 0xb0,
	0x65, 0x3e, 0x9c, 0x19, 0xf8, 0xe6, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x77, 0xd5, 0x6b,
	0xdd, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResponse, error)
	UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResponse, error)
	ReadPost(ctx context.Context, in *ReadPostReq, opts ...grpc.CallOption) (*ReadPostResponse, error)
	DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResponse, error)
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
}

type addServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddServiceClient(cc grpc.ClientConnInterface) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/proto.AddService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*UpdatePostResponse, error) {
	out := new(UpdatePostResponse)
	err := c.cc.Invoke(ctx, "/proto.AddService/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) ReadPost(ctx context.Context, in *ReadPostReq, opts ...grpc.CallOption) (*ReadPostResponse, error) {
	out := new(ReadPostResponse)
	err := c.cc.Invoke(ctx, "/proto.AddService/ReadPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*DeletePostResponse, error) {
	out := new(DeletePostResponse)
	err := c.cc.Invoke(ctx, "/proto.AddService/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := c.cc.Invoke(ctx, "/proto.AddService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddServiceServer is the server API for AddService service.
type AddServiceServer interface {
	CreatePost(context.Context, *CreatePostReq) (*CreatePostResponse, error)
	UpdatePost(context.Context, *UpdatePostReq) (*UpdatePostResponse, error)
	ReadPost(context.Context, *ReadPostReq) (*ReadPostResponse, error)
	DeletePost(context.Context, *DeletePostReq) (*DeletePostResponse, error)
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
}

// UnimplementedAddServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAddServiceServer struct {
}

func (*UnimplementedAddServiceServer) CreatePost(ctx context.Context, req *CreatePostReq) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedAddServiceServer) UpdatePost(ctx context.Context, req *UpdatePostReq) (*UpdatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (*UnimplementedAddServiceServer) ReadPost(ctx context.Context, req *ReadPostReq) (*ReadPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPost not implemented")
}
func (*UnimplementedAddServiceServer) DeletePost(ctx context.Context, req *DeletePostReq) (*DeletePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedAddServiceServer) ReadAll(ctx context.Context, req *ReadAllRequest) (*ReadAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAll not implemented")
}

func RegisterAddServiceServer(s *grpc.Server, srv AddServiceServer) {
	s.RegisterService(&_AddService_serviceDesc, srv)
}

func _AddService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).CreatePost(ctx, req.(*CreatePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).UpdatePost(ctx, req.(*UpdatePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_ReadPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).ReadPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/ReadPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).ReadPost(ctx, req.(*ReadPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).DeletePost(ctx, req.(*DeletePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AddService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _AddService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _AddService_UpdatePost_Handler,
		},
		{
			MethodName: "ReadPost",
			Handler:    _AddService_ReadPost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _AddService_DeletePost_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _AddService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
